# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.9

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/cmake-3.9.2/bin/cmake

# The command to remove a file.
RM = /usr/local/cmake-3.9.2/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/travis/build/tobylane/CorsixTH

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/travis/build/tobylane/CorsixTH/fresh

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/cmake-3.9.2/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/cmake-3.9.2/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.9.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/cmake-3.9.2/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.9.2/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/cmake-3.9.2/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.9.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/cmake-3.9.2/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/tobylane/CorsixTH/fresh/CMakeFiles /home/travis/build/tobylane/CorsixTH/fresh/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/travis/build/tobylane/CorsixTH/fresh/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named doc_leveledit

# Build rule for target.
doc_leveledit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_leveledit
.PHONY : doc_leveledit

# fast build rule for target.
doc_leveledit/fast:
	$(MAKE) -f CMakeFiles/doc_leveledit.dir/build.make CMakeFiles/doc_leveledit.dir/build
.PHONY : doc_leveledit/fast

#=============================================================================
# Target rules for targets named doc

# Build rule for target.
doc: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc
.PHONY : doc

# fast build rule for target.
doc/fast:
	$(MAKE) -f CMakeFiles/doc.dir/build.make CMakeFiles/doc.dir/build
.PHONY : doc/fast

#=============================================================================
# Target rules for targets named doc_corsixth_lua

# Build rule for target.
doc_corsixth_lua: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_corsixth_lua
.PHONY : doc_corsixth_lua

# fast build rule for target.
doc_corsixth_lua/fast:
	$(MAKE) -f CMakeFiles/doc_corsixth_lua.dir/build.make CMakeFiles/doc_corsixth_lua.dir/build
.PHONY : doc_corsixth_lua/fast

#=============================================================================
# Target rules for targets named doc_animview

# Build rule for target.
doc_animview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_animview
.PHONY : doc_animview

# fast build rule for target.
doc_animview/fast:
	$(MAKE) -f CMakeFiles/doc_animview.dir/build.make CMakeFiles/doc_animview.dir/build
.PHONY : doc_animview/fast

#=============================================================================
# Target rules for targets named doc_corsixth_engine

# Build rule for target.
doc_corsixth_engine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 doc_corsixth_engine
.PHONY : doc_corsixth_engine

# fast build rule for target.
doc_corsixth_engine/fast:
	$(MAKE) -f CMakeFiles/doc_corsixth_engine.dir/build.make CMakeFiles/doc_corsixth_engine.dir/build
.PHONY : doc_corsixth_engine/fast

#=============================================================================
# Target rules for targets named CorsixTH

# Build rule for target.
CorsixTH: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 CorsixTH
.PHONY : CorsixTH

# fast build rule for target.
CorsixTH/fast:
	$(MAKE) -f CorsixTH/CMakeFiles/CorsixTH.dir/build.make CorsixTH/CMakeFiles/CorsixTH.dir/build
.PHONY : CorsixTH/fast

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... doc_leveledit"
	@echo "... doc"
	@echo "... doc_corsixth_lua"
	@echo "... edit_cache"
	@echo "... doc_animview"
	@echo "... rebuild_cache"
	@echo "... install/strip"
	@echo "... doc_corsixth_engine"
	@echo "... list_install_components"
	@echo "... install"
	@echo "... install/local"
	@echo "... CorsixTH"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

